export type GameStage =
	| 'evacuation'
	| 'at_workshop'
	| 'packet_ready'
	| 'prototype_complete'
	| 'route_ready'
	| 'route_in_transit'
	| 'at_interchange'
	| 'interchange_scanned'
	| 'transit_connected'
	| 'act_two_complete'
	| 'act_three_travel'
	| 'at_service_corridor'
	| 'corridor_scanned'
	| 'flow_ready'
	| 'act_three_complete'
	| 'carrier_ready'
	| 'carrier_locked'
	| 'hush_departure'
	| 'hush_streets'
	| 'hush_loudspeakers'
	| 'hush_dead_zone'
	| 'hush_approach'
	| 'encounter'
	| 'unknown';

export type GameEvent =
	| 'none'
	| 'help'
	| 'status'
	| 'map'
	| 'scan_annex'
	| 'scan_workshop'
	| 'move_workshop'
	| 'move_unknown'
	| 'move_while_connected'
	| 'already_at_workshop'
	| 'connect_success'
	| 'connect_unknown'
	| 'connect_wrong_location'
	| 'already_connected'
	| 'messages_broken'
	| 'messages_recovered'
	| 'story_log'
	| 'inspect_success'
	| 'inspect_need_connection'
	| 'inspect_unknown'
	| 'evidence_capture'
	| 'evidence_protocol'
	| 'evidence_diagnostic'
	| 'evidence_integrity'
	| 'evidence_usage'
	| 'operation_not_ready'
	| 'hint_menu'
	| 'hint_no_operation'
	| 'hint_one'
	| 'hint_two'
	| 'hint_three'
	| 'hint_four'
	| 'hint_five'
	| 'hint_usage'
	| 'repair_valid'
	| 'repair_format_invalid'
	| 'repair_impossible'
	| 'act_two_begin'
	| 'route_hint_menu'
	| 'route_hint_one'
	| 'route_hint_two'
	| 'route_hint_three'
	| 'route_hint_four'
	| 'route_hint_five'
	| 'route_format_invalid'
	| 'route_impossible'
	| 'route_suboptimal'
	| 'route_optimal'
	| 'route_market'
	| 'route_bridge'
	| 'route_depot'
	| 'route_tunnel'
	| 'route_plaza'
	| 'route_rail'
	| 'route_arrival'
	| 'scan_interchange'
	| 'connect_transit_need_scan'
	| 'connect_transit_success'
	| 'transit_intel_recovered'
	| 'act_three_begin'
	| 'service_corridor_arrival'
	| 'scan_corridor'
	| 'connect_corridor_need_scan'
	| 'connect_corridor_success'
	| 'flow_format_invalid'
	| 'flow_impossible'
	| 'flow_insufficient'
	| 'flow_suboptimal'
	| 'flow_optimal'
	| 'flow_hint_menu'
	| 'flow_hint_one'
	| 'flow_hint_two'
	| 'flow_hint_three'
	| 'flow_hint_four'
	| 'flow_hint_five'
	| 'act_four_begin'
	| 'connect_carrier_success'
	| 'beacon_evidence_context'
	| 'beacon_evidence_capture'
	| 'beacon_evidence_diagnostic'
	| 'beacon_evidence_protocol'
	| 'beacon_evidence_policy'
	| 'beacon_hint_menu'
	| 'beacon_hint_one'
	| 'beacon_hint_two'
	| 'beacon_hint_three'
	| 'beacon_hint_four'
	| 'beacon_hint_five'
	| 'tune_format_invalid'
	| 'tune_impossible'
	| 'tune_valid'
	| 'carrier_failure'
	| 'hush_begin'
	| 'hush_streets'
	| 'hush_loudspeakers'
	| 'hush_dead_zone'
	| 'hush_transmitter'
	| 'reunion'
	| 'disconnected'
	| 'not_connected'
	| 'waited'
	| 'failure'
	| 'quit'
	| 'unknown_command'
	| 'internal_error'
	| 'unknown';

export interface GameSnapshot {
	seed: string;
	window: number;
	running: boolean;
	captureViewed: boolean;
	signalReviewed: boolean;
	location: string;
	connection: string;
	stage: GameStage;
	exposure: string;
	event: GameEvent;
	objective: string;
	nextCommand: string;
	detail: string;
	evidence: string;
	raw: boolean;
}

export interface OdinEngine {
	dispatch(command: string): void;
	reset(seed: bigint): void;
	destroy(): void;
}

export type SnapshotListener = (snapshot: GameSnapshot) => void;
